POST http://localhost:3000/api/order/
content-type: application/json

{
  "dishes": [
    {"id":"f4560993-2038-4e2c-8524-5b88faeecf77",
    "price": 6.0,
	"quantity": 3}
  ],
		"tax":       0.10
}
###

DELETE  http://localhost:3000/api/order/65b2bf11ae4696acdd36edca
content-type: application/json

###

GET   http://localhost:3000/api/order
content-type: application/json